version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: katablok
      POSTGRES_PASSWORD: katablok
      POSTGRES_DB: katablok
    ports:
      - "5432:5432"
    command: >
      postgres -c listen_addresses='*'
  dbAdmin: 
    image: dpage/pgadmin4:8
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@katablok.com
      PGADMIN_DEFAULT_PASSWORD: katablok
    ports:
      - "5050:80"

volumes:
  postgres_data:
  pgadmin_data:
